[package]
name = "Numen_CTF"
version = "0.0.0"

[dependencies]
MoveNursery = { git = "https://github.com/move-language/move.git",  rev = "main" , subdir = "language/move-stdlib/nursery" }
[addresses]
std =  "0x1"